module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Heinous',
    'Fraudulent',
    'Cascade',
    'Tumbling',
    'Chymous',
    'Redwood',
    'Egregious',
    'Maple',
    'Misty',
    'Sinister',
    'Luscious',
    'Ocean',
    'Sea',
    'Vacuous',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]